FROM node:22-alpine AS base
RUN corepack enable
RUN corepack prepare yarn@4.3.1 --activate
RUN apk add --no-cache git
WORKDIR /app
COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
RUN yarn install --immutable --inline-builds
COPY . .
ARG NEXT_PUBLIC_AUTH0_API_AUDIENCE
ARG NEXT_PUBLIC_AUTH0_CLIENT_ID
ARG NEXT_PUBLIC_AUTH0_DOMAIN
ARG NEXT_PUBLIC_CONVEX_URL
ENV NEXT_PUBLIC_AUTH0_API_AUDIENCE=$NEXT_PUBLIC_AUTH0_API_AUDIENCE
ENV NEXT_PUBLIC_AUTH0_CLIENT_ID=$NEXT_PUBLIC_AUTH0_CLIENT_ID
ENV NEXT_PUBLIC_AUTH0_DOMAIN=$NEXT_PUBLIC_AUTH0_DOMAIN
ENV NEXT_PUBLIC_CONVEX_URL=$NEXT_PUBLIC_CONVEX_URL
ENV NEXT_PUBLIC_ENV="production"
ENV NEXT_PUBLIC_IS_AUTH_ENABLED="true"
ENV NEXT_PUBLIC_PERSISTENCE_ENABLED="true"
ENV NEXT_PUBLIC_USE_MOCK_USER_IF_AUTH_DISABLED="false"
RUN yarn build
EXPOSE 3000
CMD ["yarn", "start"]

