version: '3.9'

x-app: &app
  image: ${NODEBOOK_IMAGE:-nodebook:latest}
  restart: unless-stopped
  env_file:
    - .env.common

services:
  nodebook-main:
    <<: *app
    container_name: nodebook-edge
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"

  nodebook-test:
    <<: *app
    container_name: nodebook-test
    environment:
      NODE_ENV: production
    ports:
      - "3001:3000"

