declare const styles: {
  readonly BottomAlign: string;
  readonly ControlsBar: string;
  readonly ControlsBarWrapper: string;
  readonly FiltersDropdown: string;
  readonly Icon: string;
  readonly PopoverButton: string;
  readonly PopoverButtonsContainer: string;
  readonly PopoverHeader: string;
  readonly RightWrapper: string;
  readonly ShowTooltip: string;
  readonly SwitchItem: string;
  readonly Button: string;
  readonly ControlsBar: string;
  readonly ControlsBarWrapper: string;
  readonly FiltersDropdown: string;
  readonly SortOptionDropdown: string;
  readonly PopoverButton: string;
  readonly PopoverButtonsContainer: string;
  readonly PopoverHeader: string;
  readonly PopoverWrapper: string;
  readonly SwitchItem: string;
};
export = styles;
