declare const styles: {
  readonly "Breadcrumb": string;
  readonly "BreadcrumbContentForMiddleRow": string;
  readonly "EmptySpaceClickArea": string;
  readonly "FloatingActionButton": string;
  readonly "HeadingContainer": string;
  readonly "HeadingLeftHandler": string;
  readonly "IconAndTitle": string;
  readonly "LinkButton": string;
  readonly "MainAndSidebarContainer": string;
  readonly "MenuIcon": string;
  readonly "MenuTrigger": string;
  readonly "MenuTriggerVisible": string;
  readonly "MiddleRow": string;
  readonly "MiddleRowBlock": string;
  readonly "Nodes": string;
  readonly "NoteContentSection": string;
  readonly "OutlineContent": string;
  readonly "RelationHeader": string;
  readonly "RelationObject": string;
  readonly "RelationObjects": string;
  readonly "RelationType": string;
  readonly "Separator": string;
  readonly "TitleContainer": string;
  readonly "TitleText": string;
  readonly "TooltipContent": string;
  readonly "Transparent": string;
  readonly "WindowNav": string;
};
export = styles;

