declare const styles: {
  readonly "Button": string;
  readonly "ButtonContainer": string;
  readonly "ButtonIcon": string;
  readonly "EmptyMessage": string;
  readonly "ExpandButton": string;
  readonly "HeaderButton": string;
  readonly "HeaderControls": string;
  readonly "HeaderLeft": string;
  readonly "IconButton": string;
  readonly "IconExpanded": string;
  readonly "IconRotated": string;
  readonly "IconsContainer": string;
  readonly "NodeCount": string;
  readonly "PinButton": string;
  readonly "PinButtonHover": string;
  readonly "PinIcon": string;
  readonly "Pinned": string;
  readonly "SearchContainer": string;
  readonly "SearchIcon": string;
  readonly "SearchInput": string;
  readonly "SearchInputActive": string;
  readonly "SearchInputIcon": string;
  readonly "SearchInputWrapper": string;
  readonly "Selected": string;
  readonly "SidebarTreeBlock": string;
  readonly "SidebarTreeChildren": string;
  readonly "SidebarTreeContainer": string;
  readonly "SidebarTreeContent": string;
};
export = styles;

