name: Vercel PostgresSQL Backup

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  auto_backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL client and AWS CLI
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/postgres.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-client-16
          sudo apt-get install -y awscli

      - name: Dump the database
        env:
          PROD_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MEW_LITE_DATABASE_URL: ${{ secrets.MEW_LITE_DATABASE_URL }}
        run: |
          /usr/lib/postgresql/16/bin/pg_dump -Fc -Z1 -v -d $PROD_DATABASE_URL -f prod_dump.bak
          /usr/lib/postgresql/16/bin/pg_dump -Fc -Z1 -v -d $MEW_LITE_DATABASE_URL -f mew_lite_dump.bak
          ls -la

      - name: Upload db dump to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-1
        run: |
          aws s3 cp prod_dump.bak s3://mew-vercel-backup/prod_dump-$(date +%F-%H-%M).bak
          aws s3 cp mew_lite_dump.bak s3://mew-vercel-backup/mew_lite_dump-$(date +%F-%H-%M).bak