name: Vercel PostgresSQL Migration
on:
  push:
    branches:
      - main
    paths:
      - 'drizzle/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Run migration(s)
        env:
          POSTGRES_CUSTOM_URL: ${{ secrets.DATABASE_URL }}
        run: yarn db:migrate
