declare const styles: {
  readonly "Bullet": string;
  readonly "BulletShadow": string;
  readonly "Circle": string;
  readonly "CirclePrivate": string;
  readonly "ClickToCreateNode": string;
  readonly "DotInsideClickToCreateNode": string;
  readonly "DotInsidePrivate": string;
  readonly "DotInsidePublic": string;
  readonly "DotOutsidePrivate": string;
  readonly "DotOutsidePublic": string;
  readonly "Hidden": string;
  readonly "HoverCardTrigger": string;
  readonly "PinIcon": string;
  readonly "PinToggle": string;
  readonly "Pinned": string;
  readonly "Placeholder": string;
  readonly "RelatedObjectActions": string;
  readonly "RelatedObjectBulletContainer": string;
  readonly "RelatedObjectContainer": string;
  readonly "RelatedObjectContent": string;
  readonly "RelatedObjectInputSuffix": string;
  readonly "RelatedObjectLeftArea": string;
  readonly "RelatedObjectLeftHandler": string;
  readonly "RelatedObjectNode": string;
  readonly "RelatedObjectNodeContent": string;
  readonly "RelatedObjectPublic": string;
  readonly "RelatedObjectRightArea": string;
  readonly "RelationCounter": string;
  readonly "RelationHoverCard": string;
  readonly "Selected": string;
  readonly "Unpinned": string;
  readonly "bulletClick": string;
};
export = styles;

